privatemessage:
  fromformat: '&dTo [&r%player%&d]: &d%message%'
  toformat: '&d[&r%player%&d] whispers: &d%message%'
messageformat: '<%player%> %message%'
spawn:
  world: 'world'
  x: '0.0'
  y: '100.0'
  z: '0.0'
  yaw: '0.0'
  pitch: '0.0'
  join: false
prefix:
  admin: '&7[&cAdmin&7] '
  mod: '&7[&9Mod&7] '