name: BlastAdmin
version: 1.0.0
author: hayatarou_

main: com.github.tckz916.blastadmin.BlastAdmin

commands:
  blastadmin:
    description: Help Command
  day:
    description: Time Command
  night:
    description: Time Command
  serverinfo:
    description: ServerInfo Command
    aliases: si
  tp:
    description: Teleport Command
  tpa:
    description: Teleport Command
  tphere:
    description: Teleport Command
  tell:
    description: PrivateMessage Command
    aliases: [whispers,w,pm,msg]
  reply:
    description: PrivateMessage Command
    aliases: r
  whois:
    description: Whois Command
permissions:
  blastadmin.admin:
    description:
    default: op
    children:
      blastadmin.command.help: true
      blastadmin.command.tp: true
      blastadmin.command.whois: true
      blastadmin.command.tell: true
      blastadmin.command.serverinfo: true
      blastadmin.command.day: true
      blastadmin.command.night: true
  blastadmin.command.help:
    default: op
  blastadmin.command.tp:
    default: op
  blastadmin.command.whois:
    default: op
  blastadmin.command.tell:
    default: op
  blastadmin.command.serverinfo:
    default: op
  blastadmin.command.day:
    default: op
  blastadmin.command.night:
    default: op

