name: BlastAdmin
version: 1.0.0
author: hayatarou_

main: com.github.tckz916.blastadmin.BlastAdmin

commands:
  blastadmin:
    description: Help Command
  tp:
    description: Teleport Command
  tphere:
    description: Teleport Command
  whois:
    description: Whois Command
permissions:
  blastadmin.admin:
    description:
    default: op
    children:
      blastadmin.command.help: true
      blastadmin.command.tp: true
      blastadmin.command.whois: true
  blastadmin.command.help:
    default: op
  blastadmin.command.tp:
    default: op
  blastadmin.command.whois:
      default: op

