name: BlastAdmin
version: 1.0.0
author: hayatarou_

main: com.github.tckz916.blastadmin.BlastAdmin

commands:
  blastadmin:
    description: Help Command
  day:
    description: Time Command
  gamemode:
    description: Gamemode Command
    aliases: gm
  iteminfo:
    description: Item Command
    aliases: ii
  night:
    description: Time Command
  mobhead:
    description: Item Command
  prefix:
    description: Prefix Command
  serverinfo:
    description: ServerInfo Command
    aliases: si
  setspawn:
    description: Teleport Command
  spawn:
    description: Teleport Command
  tp:
    description: Teleport Command
  tpa:
    description: Teleport Command
  tphere:
    description: Teleport Command
  tell:
    description: PrivateMessage Command
    aliases: [whispers,w,pm,msg]
  reply:
    description: PrivateMessage Command
    aliases: r
  whois:
    description: Whois Command
permissions:
  blastadmin.admin:
    description:
    default: op
    children:
      blastadmin.command.help: true
      blastadmin.command.tp: true
      blastadmin.command.whois: true
      blastadmin.command.tell: true
      blastadmin.command.serverinfo: true
      blastadmin.command.day: true
      blastadmin.command.night: true
      blastadmin.command.mobhead: true
      blastadmin.command.prefix: true
      blastadmin.command.setspawn: true
      blastadmin.command.spawn: true
      blastadmin.command.gamemode: true
  blastadmin.command.help:
    default: op
  blastadmin.command.tp:
    default: op
  blastadmin.command.whois:
    default: op
  blastadmin.command.tell:
    default: op
  blastadmin.command.serverinfo:
    default: op
  blastadmin.command.day:
    default: op
  blastadmin.command.night:
    default: op
  blastadmin.command.mobhead:
    default: op
  blastadmin.command.prefix:
   default: op
  blastadmin.command.setspawn:
   default: op
  blastadmin.command.spawn:
   default: op
  blastadmin.command.gamemode:
   default: op

